### ISSUE TITLE
StarUML to PlantUML diagrams

### ISSUE THREAD

**Issue by VasBu** [metanorma/metanorma-model-rsd#1]
Convert metanorma RSD StarUML diagrams to PlantUML diagrams

**Comment by VasBu** [comment]
@ronaldtse , please find the zip archives that include the results of conversion.
- [PNG.zip](https://github.com/riboseinc/metanorma-model-rsd/files/2317172/PNG.zip)
- [Source Files.zip](https://github.com/riboseinc/metanorma-model-rsd/files/2317173/Source.Files.zip)
- [SVG.zip](https://github.com/riboseinc/metanorma-model-rsd/files/2317174/SVG.zip)

**Comment by ronaldtse** [comment]
Done in 882c36235064f0508f7c3010dd7df14acbeb9b0b. Thanks @VasBu !
